[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.7",
    "scalar-fastapi>=1.0.3",
]
